# Generated by Django 4.2.2 on 2023-06-18 17:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_student_supervisor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="student_image"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="teacher_image"
            ),
        ),
    ]
