# Generated by Django 4.2.2 on 2023-06-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_student_image_alter_teacher_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="github",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="github",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
