# Generated by Django 4.2.2 on 2023-07-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_alter_report_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="activity",
            field=models.TextField(
                help_text="Provide a detailed description of the activities you have performed."
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="problems",
            field=models.TextField(
                blank=True,
                help_text="Describe any challenges or difficulties you encountered during the activities.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="response",
            field=models.TextField(
                blank=True,
                help_text="Add any response or feedback received related to the report, if applicable.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="solutions",
            field=models.TextField(
                blank=True,
                help_text="If you were able to solve the problems, explain the solutions or approaches you used. If not, indicate the steps you took or any progress made towards finding a solution.",
                null=True,
            ),
        ),
    ]
