# Generated by Django 4.2.2 on 2023-06-26 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tasksubmission",
            options={"ordering": ["-created_at"]},
        ),
    ]
