# Generated by Django 4.2.2 on 2023-06-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_alter_tasksubmission_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="overdue",
            field=models.BooleanField(default=False),
        ),
    ]
