# Generated by Django 4.2.2 on 2023-07-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_task_deadline_task_overdue"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasksubmission",
            name="links",
            field=models.URLField(
                blank=True,
                help_text="Enter the URL for the links to your answer e.g Github link.",
                max_length=500,
                null=True,
            ),
        ),
    ]
