# Generated by Django 4.2.2 on 2023-07-02 20:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_tasksubmission_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasksubmission",
            name="answer",
            field=models.TextField(
                blank=True,
                help_text="Provide a comprehensive and well-structured answer to the task, demonstrating your understanding and skills.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tasksubmission",
            name="document",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Upload any relevant documents or files that support your answer, if applicable.",
                max_length=255,
                null=True,
                verbose_name="submission",
            ),
        ),
        migrations.AlterField(
            model_name="tasksubmission",
            name="links",
            field=models.URLField(
                blank=True,
                help_text="Enter the URL for additional resources or references related to your answer (e.g., GitHub link).",
                max_length=500,
                null=True,
            ),
        ),
    ]
