# Generated by Django 4.2.2 on 2023-07-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0007_alter_tasksubmission_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasksubmission",
            name="answer",
            field=models.TextField(
                blank=True,
                help_text="Provide a comprehensive and well-structured answer to the task, demonstrating your understanding and skills, if applicable",
                null=True,
            ),
        ),
    ]
